/* automatically generated by rust-bindgen 0.72.1 */

#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]

pub const TOPO_VERSION: u32 = 1;
pub const TOPO_WALK_ERR: i32 = -1;
pub const TOPO_WALK_NEXT: u32 = 0;
pub const TOPO_WALK_TERMINATE: u32 = 1;
pub const TOPO_WALK_CHILD: u32 = 1;
pub const TOPO_WALK_SIBLING: u32 = 2;
pub const TOPO_NODE_DEFAULT: u32 = 0;
pub const TOPO_NODE_FACILITY: u32 = 1;
pub const TOPO_FAC_TYPE_SENSOR: &[u8; 7] = b"sensor\0";
pub const TOPO_FAC_TYPE_INDICATOR: &[u8; 10] = b"indicator\0";
pub const TOPO_PROP_IMMUTABLE: u32 = 0;
pub const TOPO_PROP_MUTABLE: u32 = 1;
pub const TOPO_PROP_NONVOLATILE: u32 = 2;
pub const TOPO_PGROUP_PROTOCOL: &[u8; 9] = b"protocol\0";
pub const TOPO_PROP_RESOURCE: &[u8; 9] = b"resource\0";
pub const TOPO_PROP_ASRU: &[u8; 5] = b"ASRU\0";
pub const TOPO_PROP_FRU: &[u8; 4] = b"FRU\0";
pub const TOPO_PROP_MOD: &[u8; 7] = b"module\0";
pub const TOPO_PROP_PKG: &[u8; 8] = b"package\0";
pub const TOPO_PROP_LABEL: &[u8; 6] = b"label\0";
pub const TOPO_METH_FAC_ENUM: &[u8; 9] = b"fac_enum\0";
pub const TOPO_PGROUP_SYSTEM: &[u8; 7] = b"system\0";
pub const TOPO_PROP_ISA: &[u8; 4] = b"isa\0";
pub const TOPO_PROP_MACHINE: &[u8; 8] = b"machine\0";
pub const TOPO_PGROUP_IPMI: &[u8; 5] = b"ipmi\0";
pub const TOPO_PROP_GROUP: &[u8; 15] = b"property-group\0";
pub const TOPO_PROP_GROUP_NAME: &[u8; 20] = b"property-group-name\0";
pub const TOPO_PROP_GROUP_DSTAB: &[u8; 30] = b"property-group-data-stability\0";
pub const TOPO_PROP_GROUP_NSTAB: &[u8; 30] = b"property-group-name-stability\0";
pub const TOPO_PROP_GROUP_VERSION: &[u8; 23] = b"property-group-version\0";
pub const TOPO_PROP_VAL: &[u8; 9] = b"property\0";
pub const TOPO_PROP_VAL_NAME: &[u8; 14] = b"property-name\0";
pub const TOPO_PROP_VAL_VAL: &[u8; 15] = b"property-value\0";
pub const TOPO_PROP_VAL_TYPE: &[u8; 14] = b"property-type\0";
pub const TOPO_PROP_FLAG: &[u8; 14] = b"property-flag\0";
pub const TOPO_PROP_ARGS: &[u8; 5] = b"args\0";
pub const TOPO_PROP_PARGS: &[u8; 13] = b"private-args\0";
pub const TOPO_PGROUP_FACILITY: &[u8; 9] = b"facility\0";
pub const TOPO_SENSOR_READING: &[u8; 8] = b"reading\0";
pub const TOPO_SENSOR_STATE: &[u8; 6] = b"state\0";
pub const TOPO_SENSOR_CLASS: &[u8; 13] = b"sensor-class\0";
pub const TOPO_FACILITY_TYPE: &[u8; 5] = b"type\0";
pub const TOPO_SENSOR_UNITS: &[u8; 6] = b"units\0";
pub const TOPO_LED_MODE: &[u8; 5] = b"mode\0";
pub const TOPO_PROP_THRESHOLD_LNC: &[u8; 29] = b"threshold-lower-non-critical\0";
pub const TOPO_PROP_THRESHOLD_LCR: &[u8; 25] = b"threshold-lower-critical\0";
pub const TOPO_PROP_THRESHOLD_LNR: &[u8; 32] = b"threshold-lower-non-recoverable\0";
pub const TOPO_PROP_THRESHOLD_UNC: &[u8; 29] = b"threshold-upper-non-critical\0";
pub const TOPO_PROP_THRESHOLD_UCR: &[u8; 25] = b"threshold-upper-critical\0";
pub const TOPO_PROP_THRESHOLD_UNR: &[u8; 32] = b"threshold-upper-non-recoverable\0";
pub const TOPO_SENSOR_CLASS_THRESHOLD: &[u8; 10] = b"threshold\0";
pub const TOPO_SENSOR_CLASS_DISCRETE: &[u8; 9] = b"discrete\0";
pub const TOPO_PROP_REMOTE_AGENTS: &[u8; 14] = b"remote-agents\0";
pub const TOPO_SENSOR_ERRSRC_UNKNOWN: u32 = 0;
pub const TOPO_SENSOR_ERRSRC_INTERNAL: u32 = 1;
pub const TOPO_SENSOR_ERRSRC_EXTERNAL: u32 = 2;
pub const TOPO_SENSOR_TYPE_RESERVED: u32 = 0;
pub const TOPO_SENSOR_TYPE_TEMP: u32 = 1;
pub const TOPO_SENSOR_TYPE_VOLTAGE: u32 = 2;
pub const TOPO_SENSOR_TYPE_CURRENT: u32 = 3;
pub const TOPO_SENSOR_TYPE_FAN: u32 = 4;
pub const TOPO_SENSOR_TYPE_PHYSICAL: u32 = 5;
pub const TOPO_SENSOR_STATE_PHYSICAL_GENERAL: u32 = 1;
pub const TOPO_SENSOR_STATE_PHYSICAL_BAY: u32 = 2;
pub const TOPO_SENSOR_STATE_PHYSICAL_CARD: u32 = 4;
pub const TOPO_SENSOR_STATE_PHYSICAL_PROCESSOR: u32 = 8;
pub const TOPO_SENSOR_STATE_PHYSICAL_LAN: u32 = 16;
pub const TOPO_SENSOR_STATE_PHYSICAL_DOCK: u32 = 32;
pub const TOPO_SENSOR_STATE_PHYSICAL_FAN: u32 = 64;
pub const TOPO_SENSOR_TYPE_PLATFORM: u32 = 6;
pub const TOPO_SENSOR_STATE_PLATFORM_SECURE: u32 = 1;
pub const TOPO_SENSOR_STATE_PLATFORM_USER_PASS: u32 = 2;
pub const TOPO_SENSOR_STATE_PLATFORM_SETUP_PASS: u32 = 4;
pub const TOPO_SENSOR_STATE_PLATFORM_NETWORK_PASS: u32 = 8;
pub const TOPO_SENSOR_STATE_PLATFORM_OTHER_PASS: u32 = 16;
pub const TOPO_SENSOR_STATE_PLATFORM_OUT_OF_BAND: u32 = 32;
pub const TOPO_SENSOR_TYPE_PROCESSOR: u32 = 7;
pub const TOPO_SENSOR_STATE_PROCESSOR_IERR: u32 = 1;
pub const TOPO_SENSOR_STATE_PROCESSOR_THERMAL: u32 = 2;
pub const TOPO_SENSOR_STATE_PROCESSOR_FRB1: u32 = 4;
pub const TOPO_SENSOR_STATE_PROCESSOR_FRB2: u32 = 8;
pub const TOPO_SENSOR_STATE_PROCESSOR_FRB3: u32 = 16;
pub const TOPO_SENSOR_STATE_PROCESSOR_CONFIG: u32 = 32;
pub const TOPO_SENSOR_STATE_PROCESSOR_SMBIOS: u32 = 64;
pub const TOPO_SENSOR_STATE_PROCESSOR_PRESENT: u32 = 128;
pub const TOPO_SENSOR_STATE_PROCESSOR_DISABLED: u32 = 256;
pub const TOPO_SENSOR_STATE_PROCESSOR_TERMINATOR: u32 = 512;
pub const TOPO_SENSOR_STATE_PROCESSOR_THROTTLED: u32 = 1024;
pub const TOPO_SENSOR_TYPE_POWER_SUPPLY: u32 = 8;
pub const TOPO_SENSOR_STATE_POWER_SUPPLY_PRESENT: u32 = 1;
pub const TOPO_SENSOR_STATE_POWER_SUPPLY_FAILURE: u32 = 2;
pub const TOPO_SENSOR_STATE_POWER_SUPPLY_PREDFAIL: u32 = 4;
pub const TOPO_SENSOR_STATE_POWER_SUPPLY_INPUT_LOST: u32 = 8;
pub const TOPO_SENSOR_STATE_POWER_SUPPLY_INPUT_RANGE: u32 = 16;
pub const TOPO_SENSOR_STATE_POWER_SUPPLY_INPUT_RANGE_PRES: u32 = 32;
pub const TOPO_SENSOR_STATE_POWER_SUPPLY_CONFIG_ERR: u32 = 64;
pub const TOPO_SENSOR_TYPE_POWER_UNIT: u32 = 9;
pub const TOPO_SENSOR_STATE_POWER_UNIT_OFF: u32 = 1;
pub const TOPO_SENSOR_STATE_POWER_UNIT_CYCLE: u32 = 2;
pub const TOPO_SENSOR_STATE_POWER_UNIT_240_DOWN: u32 = 4;
pub const TOPO_SENSOR_STATE_POWER_UNIT_INTERLOCK_DOWN: u32 = 8;
pub const TOPO_SENSOR_STATE_POWER_UNIT_AC_LOST: u32 = 16;
pub const TOPO_SENSOR_STATE_POWER_UNIT_SOFT_FAILURE: u32 = 32;
pub const TOPO_SENSOR_STATE_POWER_UNIT_FAIL: u32 = 64;
pub const TOPO_SENSOR_STATE_POWER_UNIT_PREDFAIL: u32 = 128;
pub const TOPO_SENSOR_TYPE_COOLING: u32 = 10;
pub const TOPO_SENSOR_TYPE_OTHER: u32 = 11;
pub const TOPO_SENSOR_TYPE_MEMORY: u32 = 12;
pub const TOPO_SENSOR_STATE_MEMORY_CE: u32 = 1;
pub const TOPO_SENSOR_STATE_MEMORY_UE: u32 = 2;
pub const TOPO_SENSOR_STATE_MEMORY_PARITY: u32 = 4;
pub const TOPO_SENSOR_STATE_MEMORY_SCRUB_FAIL: u32 = 8;
pub const TOPO_SENSOR_STATE_MEMORY_DISABLED: u32 = 16;
pub const TOPO_SENSOR_STATE_MEMORY_CE_LOG_LIMIT: u32 = 32;
pub const TOPO_SENSOR_STATE_MEMORY_PRESENT: u32 = 64;
pub const TOPO_SENSOR_STATE_MEMORY_CONFIG_ERR: u32 = 128;
pub const TOPO_SENSOR_STATE_MEMORY_SPARE: u32 = 256;
pub const TOPO_SENSOR_STATE_MEMORY_THROTTLED: u32 = 512;
pub const TOPO_SENSOR_STATE_MEMORY_OVERTEMP: u32 = 1024;
pub const TOPO_SENSOR_TYPE_BAY: u32 = 13;
pub const TOPO_SENSOR_STATE_BAY_PRESENT: u32 = 1;
pub const TOPO_SENSOR_STATE_BAY_FAULT: u32 = 2;
pub const TOPO_SENSOR_STATE_BAY_PREDFAIL: u32 = 4;
pub const TOPO_SENSOR_STATE_BAY_SPARE: u32 = 8;
pub const TOPO_SENSOR_STATE_BAY_CHECK: u32 = 16;
pub const TOPO_SENSOR_STATE_BAY_CRITICAL: u32 = 32;
pub const TOPO_SENSOR_STATE_BAY_FAILED: u32 = 64;
pub const TOPO_SENSOR_STATE_BAY_REBUILDING: u32 = 128;
pub const TOPO_SENSOR_STATE_BAY_ABORTED: u32 = 256;
pub const TOPO_SENSOR_TYPE_POST_RESIZE: u32 = 14;
pub const TOPO_SENSOR_TYPE_FIRMWARE: u32 = 15;
pub const TOPO_SENSOR_STATE_FIRMWARE_ERROR: u32 = 1;
pub const TOPO_SENSOR_STATE_FIRMWARE_HANG: u32 = 2;
pub const TOPO_SENSOR_STATE_FIRMWARE_PROGRESS: u32 = 4;
pub const TOPO_SENSOR_TYPE_EVENT_LOG: u32 = 16;
pub const TOPO_SENSOR_STATE_EVENT_LOG_CE: u32 = 1;
pub const TOPO_SENSOR_STATE_EVENT_LOG_TYPE: u32 = 2;
pub const TOPO_SENSOR_STATE_EVENT_LOG_RESET: u32 = 4;
pub const TOPO_SENSOR_STATE_EVENT_LOG_ALL: u32 = 8;
pub const TOPO_SENSOR_STATE_EVENT_LOG_FULL: u32 = 16;
pub const TOPO_SENSOR_STATE_EVENT_LOG_ALMOST_FULL: u32 = 32;
pub const TOPO_SENSOR_TYPE_WATCHDOG1: u32 = 17;
pub const TOPO_SENSOR_STATE_WATCHDOG_BIOS_RESET: u32 = 1;
pub const TOPO_SENSOR_STATE_WATCHDOG_OS_RESET: u32 = 2;
pub const TOPO_SENSOR_STATE_WATCHDOG_OS_SHUTDOWN: u32 = 4;
pub const TOPO_SENSOR_STATE_WATCHDOG_OS_PWR_DOWN: u32 = 8;
pub const TOPO_SENSOR_STATE_WATCHDOG_OS_PWR_CYCLE: u32 = 16;
pub const TOPO_SENSOR_STATE_WATCHDOG_OS_NMI_DIAG: u32 = 32;
pub const TOPO_SENSOR_STATE_WATCHDOG_EXPIRED: u32 = 64;
pub const TOPO_SENSOR_STATE_WATCHDOG_PRE_TIMEOUT_INT: u32 = 128;
pub const TOPO_SENSOR_TYPE_SYSTEM: u32 = 18;
pub const TOPO_SENSOR_STATE_SYSTEM_RECONF: u32 = 1;
pub const TOPO_SENSOR_STATE_SYSTEM_BOOT: u32 = 2;
pub const TOPO_SENSOR_STATE_SYSTEM_UNKNOWN_HW_FAILURE: u32 = 4;
pub const TOPO_SENSOR_STATE_SYSTEM_AUX_LOG_UPDATED: u32 = 8;
pub const TOPO_SENSOR_STATE_SYSTEM_PEF_ACTION: u32 = 16;
pub const TOPO_SENSOR_STATE_SYSTEM_TIMETAMP_CLOCKSYNC: u32 = 32;
pub const TOPO_SENSOR_TYPE_CRITICAL: u32 = 19;
pub const TOPO_SENSOR_STATE_CRITICAL_EXT_NMI: u32 = 1;
pub const TOPO_SENSOR_STATE_CRITICAL_BUS_TIMEOUT: u32 = 2;
pub const TOPO_SENSOR_STATE_CRITICAL_IO_NMI: u32 = 4;
pub const TOPO_SENSOR_STATE_CRITICAL_SW_NMI: u32 = 8;
pub const TOPO_SENSOR_STATE_CRITICAL_PCI_PERR: u32 = 16;
pub const TOPO_SENSOR_STATE_CRITICAL_PCI_SERR: u32 = 32;
pub const TOPO_SENSOR_STATE_CRITICAL_EISA_FAILSAFE: u32 = 64;
pub const TOPO_SENSOR_STATE_CRITICAL_BUS_CE: u32 = 128;
pub const TOPO_SENSOR_STATE_CRITICAL_BUS_UE: u32 = 256;
pub const TOPO_SENSOR_STATE_CRITICAL_FATAL_NMI: u32 = 512;
pub const TOPO_SENSOR_STATE_CRITICAL_BUS_FATAL_ERR: u32 = 1024;
pub const TOPO_SENSOR_STATE_CRITICAL_BUS_DEGRADED: u32 = 2048;
pub const TOPO_SENSOR_TYPE_BUTTON: u32 = 20;
pub const TOPO_SENSOR_STATE_BUTTON_PWR: u32 = 1;
pub const TOPO_SENSOR_STATE_BUTTON_SLEEP: u32 = 2;
pub const TOPO_SENSOR_STATE_BUTTON_RESET: u32 = 4;
pub const TOPO_SENSOR_STATE_BUTTON_FRU_LATCH: u32 = 8;
pub const TOPO_SENSOR_STATE_BUTTON_FRU_SERVICE: u32 = 16;
pub const TOPO_SENSOR_TYPE_MODULE: u32 = 21;
pub const TOPO_SENSOR_TYPE_MICROCONTROLLER: u32 = 22;
pub const TOPO_SENSOR_TYPE_CARD: u32 = 23;
pub const TOPO_SENSOR_TYPE_CHASSIS: u32 = 24;
pub const TOPO_SENSOR_TYPE_CHIPSET: u32 = 25;
pub const TOPO_SENSOR_STATE_CHIPSET_PWR_CTL_FAIL: u32 = 1;
pub const TOPO_SENSOR_TYPE_FRU: u32 = 26;
pub const TOPO_SENSOR_TYPE_CABLE: u32 = 27;
pub const TOPO_SENSOR_STATE_CABLE_CONNECTED: u32 = 1;
pub const TOPO_SENSOR_STATE_CABLE_CONFIG_ERR: u32 = 2;
pub const TOPO_SENSOR_TYPE_TERMINATOR: u32 = 28;
pub const TOPO_SENSOR_TYPE_BOOT_STATE: u32 = 29;
pub const TOPO_SENSOR_STATE_BOOT_STATE_BIOS_PWR_UP: u32 = 1;
pub const TOPO_SENSOR_STATE_BOOT_STATE_BIOS_HARD_RESET: u32 = 2;
pub const TOPO_SENSOR_STATE_BOOT_STATE_BIOS_WARM_RESET: u32 = 4;
pub const TOPO_SENSOR_STATE_BOOT_STATE_PXE_BOOT: u32 = 8;
pub const TOPO_SENSOR_STATE_BOOT_STATE_DIAG_BOOT: u32 = 16;
pub const TOPO_SENSOR_STATE_BOOT_STATE_OS_HARD_RESET: u32 = 32;
pub const TOPO_SENSOR_STATE_BOOT_STATE_OS_WARM_RESET: u32 = 64;
pub const TOPO_SENSOR_STATE_BOOT_STATE_SYS_RESTART: u32 = 128;
pub const TOPO_SENSOR_TYPE_BOOT_ERROR: u32 = 30;
pub const TOPO_SENSOR_STATE_BOOT_ERROR_NOMEDIA: u32 = 1;
pub const TOPO_SENSOR_STATE_BOOT_ERROR_NON_BOOTABLE_DISK: u32 = 2;
pub const TOPO_SENSOR_STATE_BOOT_ERROR_NO_PXE_SERVER: u32 = 4;
pub const TOPO_SENSOR_STATE_BOOT_ERROR_INV_BOOT_SECT: u32 = 8;
pub const TOPO_SENSOR_STATE_BOOT_ERROR_USR_SELECT_TIMEOUT: u32 = 16;
pub const TOPO_SENSOR_TYPE_BOOT_OS: u32 = 31;
pub const TOPO_SENSOR_STATE_BOOT_OS_A_DRV_BOOT_COMPLETE: u32 = 1;
pub const TOPO_SENSOR_STATE_BOOT_OS_C_DRV_BOOT_COMPLETE: u32 = 2;
pub const TOPO_SENSOR_STATE_BOOT_OS_PXE_BOOT_COMPLETE: u32 = 4;
pub const TOPO_SENSOR_STATE_BOOT_OS_DIAG_BOOT_COMPLETE: u32 = 8;
pub const TOPO_SENSOR_STATE_BOOT_OS_CDROM_BOOT_COMPLETE: u32 = 16;
pub const TOPO_SENSOR_STATE_BOOT_OS_ROM_BOOT_COMPLETE: u32 = 32;
pub const TOPO_SENSOR_STATE_BOOT_OS_UNSPEC_BOOT_COMPLETE: u32 = 64;
pub const TOPO_SENSOR_TYPE_OS_SHUTDOWN: u32 = 32;
pub const TOPO_SENSOR_STATE_OS_SHUTDOWN_LOADING: u32 = 1;
pub const TOPO_SENSOR_STATE_OS_SHUTDOWN_CRASH: u32 = 2;
pub const TOPO_SENSOR_STATE_OS_STOP_GRACEFUL: u32 = 4;
pub const TOPO_SENSOR_STATE_OS_SHUTDOWN_GRACEFUL: u32 = 8;
pub const TOPO_SENSOR_STATE_OS_SHUTDOWN_PEF: u32 = 16;
pub const TOPO_SENSOR_STATE_OS_SHUTDOWN_BMC: u32 = 32;
pub const TOPO_SENSOR_TYPE_SLOT: u32 = 33;
pub const TOPO_SENSOR_STATE_SLOT_FAULT_ASSERTED: u32 = 1;
pub const TOPO_SENSOR_STATE_SLOT_IDENTIFY_ASSERTED: u32 = 2;
pub const TOPO_SENSOR_STATE_SLOT_CONNECTED: u32 = 4;
pub const TOPO_SENSOR_STATE_SLOT_INSTALL_READY: u32 = 8;
pub const TOPO_SENSOR_STATE_SLOT_REMOVE_READY: u32 = 16;
pub const TOPO_SENSOR_STATE_SLOT_PWR_OFF: u32 = 32;
pub const TOPO_SENSOR_STATE_SLOT_REMOVED: u32 = 64;
pub const TOPO_SENSOR_STATE_SLOT_INTERLOCK_ASSERTED: u32 = 128;
pub const TOPO_SENSOR_STATE_SLOT_DISABLED: u32 = 256;
pub const TOPO_SENSOR_STATE_SLOT_SPARE_DEVICE: u32 = 512;
pub const TOPO_SENSOR_TYPE_ACPI: u32 = 34;
pub const TOPO_SENSOR_STATE_ACPI_PSTATE_S0_G0: u32 = 1;
pub const TOPO_SENSOR_STATE_ACPI_PSTATE_S1: u32 = 2;
pub const TOPO_SENSOR_STATE_ACPI_PSTATE_S2: u32 = 4;
pub const TOPO_SENSOR_STATE_ACPI_PSTATE_S3: u32 = 8;
pub const TOPO_SENSOR_STATE_ACPI_PSTATE_S4: u32 = 16;
pub const TOPO_SENSOR_STATE_ACPI_PSTATE_S5_G2_SOFT_OFF: u32 = 32;
pub const TOPO_SENSOR_STATE_ACPI_PSTATE_S4_S5_SOFT_OFF: u32 = 64;
pub const TOPO_SENSOR_STATE_ACPI_PSATTE_G3_MECH_OFF: u32 = 128;
pub const TOPO_SENSOR_STATE_ACPI_PSTATE_S1_S2_S3_SLEEP: u32 = 256;
pub const TOPO_SENSOR_STATE_ACPI_PSTATE_G1_SLEEP: u32 = 512;
pub const TOPO_SENSOR_STATE_ACPI_PSTATE_S5_OVERRIDE: u32 = 1024;
pub const TOPO_SENSOR_STATE_ACPI_PSTATE_LEGACY_ON: u32 = 2048;
pub const TOPO_SENSOR_STATE_ACPI_PSTATE_LEGACY_OFF: u32 = 4096;
pub const TOPO_SENSOR_STATE_ACPI_PSTATE_UNKNOWN: u32 = 8192;
pub const TOPO_SENSOR_TYPE_WATCHDOG2: u32 = 35;
pub const TOPO_SENSOR_STATE_WATCHDOG2_EXPIRED: u32 = 1;
pub const TOPO_SENSOR_STATE_WATCHDOG2_HARD_RESET: u32 = 2;
pub const TOPO_SENSOR_STATE_WATCHDOG2_PWR_DOWN: u32 = 4;
pub const TOPO_SENSOR_STATE_WATCHDOG2_PWR_CYCLE: u32 = 8;
pub const TOPO_SENSOR_STATE_WATCHDOG2_RESERVED1: u32 = 16;
pub const TOPO_SENSOR_STATE_WATCHDOG2_RESERVED2: u32 = 32;
pub const TOPO_SENSOR_STATE_WATCHDOG2_RESERVED3: u32 = 64;
pub const TOPO_SENSOR_STATE_WATCHDOG2_RESERVED4: u32 = 128;
pub const TOPO_SENSOR_STATE_WATCHDOG2_TIMEOUT_INT: u32 = 256;
pub const TOPO_SENSOR_TYPE_ALERT: u32 = 36;
pub const TOPO_SENSOR_STATE_ALERT_PLAT_PAGE: u32 = 1;
pub const TOPO_SENSOR_STATE_ALERT_PLAT_LAN_ALERT: u32 = 2;
pub const TOPO_SENSOR_STATE_ALERT_PLAT_EVT_TRAP: u32 = 4;
pub const TOPO_SENSOR_STATE_ALERT_PLAT_SNMP_TRAP: u32 = 8;
pub const TOPO_SENSOR_TYPE_PRESENCE: u32 = 37;
pub const TOPO_SENSOR_STATE_PRESENCE_PRESENT: u32 = 1;
pub const TOPO_SENSOR_STATE_PRESENCE_ABSENT: u32 = 2;
pub const TOPO_SENSOR_STATE_PRESENCE_DISABLED: u32 = 4;
pub const TOPO_SENSOR_TYPE_ASIC: u32 = 38;
pub const TOPO_SENSOR_TYPE_LAN: u32 = 39;
pub const TOPO_SENSOR_STATE_LAN_HEARTBEAT_LOST: u32 = 1;
pub const TOPO_SENSOR_STATE_LAN_HEARTBEAT: u32 = 2;
pub const TOPO_SENSOR_TYPE_HEALTH: u32 = 40;
pub const TOPO_SENSOR_STATE_HEALTH_SENSOR_ACC_DEGRADED: u32 = 1;
pub const TOPO_SENSOR_STATE_HEALTH_CNTLR_ACC_DEGRADED: u32 = 2;
pub const TOPO_SENSOR_STATE_HEALTH_CNTLR_OFFLINE: u32 = 4;
pub const TOPO_SENSOR_STATE_HEALTH_CNTLR_UNAVAIL: u32 = 8;
pub const TOPO_SENSOR_STATE_HEALTH_SENSOR_FAILURE: u32 = 16;
pub const TOPO_SENSOR_STATE_HEALTH_FRU_FAILURE: u32 = 32;
pub const TOPO_SENSOR_TYPE_BATTERY: u32 = 41;
pub const TOPO_SENSOR_STATE_BATTERY_LOW: u32 = 1;
pub const TOPO_SENSOR_STATE_BATTERY_FAILED: u32 = 2;
pub const TOPO_SENSOR_STATE_BATTERY_PRESENCE: u32 = 4;
pub const TOPO_SENSOR_TYPE_AUDIT: u32 = 42;
pub const TOPO_SENSOR_STATE_AUDIT_SESSION_ACTIVATED: u32 = 1;
pub const TOPO_SENSOR_STATE_AUDIT_SESSION_DEACTIVATED: u32 = 2;
pub const TOPO_SENSOR_TYPE_VERSION: u32 = 43;
pub const TOPO_SENSOR_STATE_VERSION_HW_CHANGE: u32 = 1;
pub const TOPO_SENSOR_STATE_VERSION_SW_CHANGE: u32 = 2;
pub const TOPO_SENSOR_STATE_VERSION_HW_INCOMPATIBLE: u32 = 4;
pub const TOPO_SENSOR_STATE_VERSION_SW_INCOMPATIBLE: u32 = 8;
pub const TOPO_SENSOR_STATE_VERSION_HW_INVAL: u32 = 16;
pub const TOPO_SENSOR_STATE_VERSION_SW_INVAL: u32 = 32;
pub const TOPO_SENSOR_STATE_VERSION_HW_CHANGE_SUCCESS: u32 = 64;
pub const TOPO_SENSOR_STATE_VERSION_SW_CHANGE_SUCCESS: u32 = 128;
pub const TOPO_SENSOR_TYPE_FRU_STATE: u32 = 44;
pub const TOPO_SENSOR_STATE_FRU_STATE_NOT_INSTALLED: u32 = 1;
pub const TOPO_SENSOR_STATE_FRU_STATE_INACTIVE: u32 = 2;
pub const TOPO_SENSOR_STATE_FRU_STATE_ACT_REQ: u32 = 4;
pub const TOPO_SENSOR_STATE_FRU_STATE_ACT_INPROGRESS: u32 = 8;
pub const TOPO_SENSOR_STATE_FRU_STATE_ACTIVE: u32 = 16;
pub const TOPO_SENSOR_STATE_FRU_STATE_DEACT_REQ: u32 = 32;
pub const TOPO_SENSOR_STATE_FRU_STATE_DEACT_INPROGRESS: u32 = 64;
pub const TOPO_SENSOR_STATE_FRU_STATE_COMM_LOST: u32 = 128;
pub const TOPO_SENSOR_TYPE_THRESHOLD_STATE: u32 = 257;
pub const TOPO_SENSOR_STATE_THRESH_LOWER_NONCRIT: u32 = 1;
pub const TOPO_SENSOR_STATE_THRESH_LOWER_CRIT: u32 = 2;
pub const TOPO_SENSOR_STATE_THRESH_LOWER_NONREC: u32 = 4;
pub const TOPO_SENSOR_STATE_THRESH_UPPER_NONCRIT: u32 = 8;
pub const TOPO_SENSOR_STATE_THRESH_UPPER_CRIT: u32 = 16;
pub const TOPO_SENSOR_STATE_THRESH_UPPER_NONREC: u32 = 32;
pub const TOPO_SENSOR_TYPE_GENERIC_USAGE: u32 = 258;
pub const TOPO_SENSOR_STATE_GENERIC_USAGE_IDLE: u32 = 1;
pub const TOPO_SENSOR_STATE_GENERIC_USAGE_ACTIVE: u32 = 2;
pub const TOPO_SENSOR_STATE_GENERIC_USAGE_BUSY: u32 = 4;
pub const TOPO_SENSOR_TYPE_GENERIC_STATE: u32 = 259;
pub const TOPO_SENSOR_STATE_GENERIC_STATE_DEASSERTED: u32 = 1;
pub const TOPO_SENSOR_STATE_GENERIC_STATE_ASSERTED: u32 = 2;
pub const TOPO_SENSOR_TYPE_GENERIC_PREDFAIL: u32 = 260;
pub const TOPO_SENSOR_STATE_GENERIC_PREDFAIL_DEASSERTED: u32 = 1;
pub const TOPO_SENSOR_STATE_GENERIC_PREDFAIL_ASSERTED: u32 = 2;
pub const TOPO_SENSOR_TYPE_GENERIC_LIMIT: u32 = 261;
pub const TOPO_SENSOR_STATE_GENERIC_LIMIT_NOT_EXCEEDED: u32 = 1;
pub const TOPO_SENSOR_STATE_GENERIC_LIMIT_EXCEEDED: u32 = 2;
pub const TOPO_SENSOR_TYPE_GENERIC_PERFORMANCE: u32 = 262;
pub const TOPO_SENSOR_STATE_GENERIC_PERFORMANCE_MET: u32 = 1;
pub const TOPO_SENSOR_STATE_GENERIC_PERFORMANCE_LAGS: u32 = 2;
pub const TOPO_SENSOR_TYPE_SEVERITY: u32 = 263;
pub const TOPO_SENSOR_STATE_SEVERITY_OK: u32 = 1;
pub const TOPO_SENSOR_STATE_SEVERITY_NONCRIT_GOING_HIGH: u32 = 2;
pub const TOPO_SENSOR_STATE_SEVERITY_CRIT_GOING_HIGH: u32 = 4;
pub const TOPO_SENSOR_STATE_SEVERITY_NONREC_GOING_HIGH: u32 = 8;
pub const TOPO_SENSOR_STATE_SEVERITY_NONCRIT_GOING_LOW: u32 = 16;
pub const TOPO_SENSOR_STATE_SEVERITY_CRIT_GOING_LOW: u32 = 32;
pub const TOPO_SENSOR_STATE_SEVERITY_NONREC_GOING_LOW: u32 = 32;
pub const TOPO_SENSOR_STATE_SEVERITY_MONITOR: u32 = 64;
pub const TOPO_SENSOR_STATE_SEVERITY_INFORMATIONAL: u32 = 128;
pub const TOPO_SENSOR_TYPE_GENERIC_PRESENCE: u32 = 264;
pub const TOPO_SENSOR_STATE_GENERIC_PRESENCE_DEASSERTED: u32 = 1;
pub const TOPO_SENSOR_STATE_GENERIC_PRESENCE_ASSERTED: u32 = 2;
pub const TOPO_SENSOR_TYPE_GENERIC_AVAILABILITY: u32 = 265;
pub const TOPO_SENSOR_STATE_GENERIC_AVAIL_DEASSERTED: u32 = 1;
pub const TOPO_SENSOR_STATE_GENERIC_AVAIL_ASSERTED: u32 = 2;
pub const TOPO_SENSOR_TYPE_GENERIC_STATUS: u32 = 266;
pub const TOPO_SENSOR_STATE_GENERIC_STATUS_RUNNING: u32 = 1;
pub const TOPO_SENSOR_STATE_GENERIC_STATUS_IN_TEST: u32 = 2;
pub const TOPO_SENSOR_STATE_GENERIC_STATUS_POWER_OFF: u32 = 4;
pub const TOPO_SENSOR_STATE_GENERIC_STATUS_ONLINE: u32 = 8;
pub const TOPO_SENSOR_STATE_GENERIC_STATUS_OFFLINE: u32 = 16;
pub const TOPO_SENSOR_STATE_GENERIC_STATUS_OFF_DUTY: u32 = 32;
pub const TOPO_SENSOR_STATE_GENERIC_STATUS_DEGRADED: u32 = 64;
pub const TOPO_SENSOR_STATE_GENERIC_STATUS_POWER_SAVE: u32 = 128;
pub const TOPO_SENSOR_STATE_GENERIC_STATUS_INSTALL_ERR: u32 = 256;
pub const TOPO_SENSOR_TYPE_GENERIC_REDUNDANCY: u32 = 267;
pub const TOPO_SENSOR_TYPE_GENERIC_ACPI: u32 = 268;
pub const TOPO_SENSOR_STATE_GENERIC_ACPI_D0: u32 = 1;
pub const TOPO_SENSOR_STATE_GENERIC_ACPI_D1: u32 = 2;
pub const TOPO_SENSOR_STATE_GENERIC_ACPI_D2: u32 = 4;
pub const TOPO_SENSOR_STATE_GENERIC_ACPI_D3: u32 = 8;
pub const TOPO_SENSOR_TYPE_GENERIC_FAILURE: u32 = 269;
pub const TOPO_SENSOR_STATE_GENERIC_FAIL_DEASSERTED: u32 = 1;
pub const TOPO_SENSOR_STATE_GENERIC_FAIL_NONRECOV: u32 = 2;
pub const TOPO_SENSOR_STATE_GENERIC_FAIL_CRITICAL: u32 = 4;
pub const TOPO_SENSOR_TYPE_GENERIC_OK: u32 = 270;
pub const TOPO_SENSOR_STATE_GENERIC_OK_DEASSERTED: u32 = 1;
pub const TOPO_SENSOR_STATE_GENERIC_OK_ASSERTED: u32 = 2;
pub const TOPO_SENSOR_TYPE_SYNTHETIC: u32 = 271;
pub const TOPO_FAC_TYPE_ANY: u32 = 4294967295;
pub const FM_CLASS: &[u8; 6] = b"class\0";
pub const FM_VERSION: &[u8; 8] = b"version\0";
pub const FM_EREPORT_CLASS: &[u8; 8] = b"ereport\0";
pub const FM_FAULT_CLASS: &[u8; 6] = b"fault\0";
pub const FM_DEFECT_CLASS: &[u8; 7] = b"defect\0";
pub const FM_RSRC_CLASS: &[u8; 9] = b"resource\0";
pub const FM_LIST_EVENT: &[u8; 5] = b"list\0";
pub const FM_IREPORT_CLASS: &[u8; 8] = b"ireport\0";
pub const FM_LIST_SUSPECT_CLASS: &[u8; 13] = b"list.suspect\0";
pub const FM_LIST_ISOLATED_CLASS: &[u8; 14] = b"list.isolated\0";
pub const FM_LIST_REPAIRED_CLASS: &[u8; 14] = b"list.repaired\0";
pub const FM_LIST_UPDATED_CLASS: &[u8; 13] = b"list.updated\0";
pub const FM_LIST_RESOLVED_CLASS: &[u8; 14] = b"list.resolved\0";
pub const FM_ERROR_CPU: &[u8; 4] = b"cpu\0";
pub const FM_ERROR_IO: &[u8; 3] = b"io\0";
pub const FM_EREPORT_VERS0: u32 = 0;
pub const FM_EREPORT_VERSION: u32 = 0;
pub const FM_EREPORT_DETECTOR: &[u8; 9] = b"detector\0";
pub const FM_EREPORT_ENA: &[u8; 4] = b"ena\0";
pub const FM_LIST_EVENT_SIZE: &[u8; 8] = b"list-sz\0";
pub const FM_IREPORT_DETECTOR: &[u8; 9] = b"detector\0";
pub const FM_IREPORT_UUID: &[u8; 5] = b"uuid\0";
pub const FM_IREPORT_PRIORITY: &[u8; 4] = b"pri\0";
pub const FM_IREPORT_ATTRIBUTES: &[u8; 5] = b"attr\0";
pub const FM_SUSPECT_UUID: &[u8; 5] = b"uuid\0";
pub const FM_SUSPECT_DIAG_CODE: &[u8; 5] = b"code\0";
pub const FM_SUSPECT_DIAG_TIME: &[u8; 10] = b"diag-time\0";
pub const FM_SUSPECT_DE: &[u8; 3] = b"de\0";
pub const FM_SUSPECT_FAULT_LIST: &[u8; 11] = b"fault-list\0";
pub const FM_SUSPECT_FAULT_SZ: &[u8; 14] = b"fault-list-sz\0";
pub const FM_SUSPECT_FAULT_STATUS: &[u8; 13] = b"fault-status\0";
pub const FM_SUSPECT_INJECTED: &[u8; 11] = b"__injected\0";
pub const FM_SUSPECT_MESSAGE: &[u8; 8] = b"message\0";
pub const FM_SUSPECT_RETIRE: &[u8; 7] = b"retire\0";
pub const FM_SUSPECT_RESPONSE: &[u8; 9] = b"response\0";
pub const FM_SUSPECT_SEVERITY: &[u8; 9] = b"severity\0";
pub const FM_SUSPECT_VERS0: u32 = 0;
pub const FM_SUSPECT_VERSION: u32 = 0;
pub const FM_SUSPECT_FAULTY: u32 = 1;
pub const FM_SUSPECT_UNUSABLE: u32 = 2;
pub const FM_SUSPECT_NOT_PRESENT: u32 = 4;
pub const FM_SUSPECT_DEGRADED: u32 = 8;
pub const FM_SUSPECT_REPAIRED: u32 = 16;
pub const FM_SUSPECT_REPLACED: u32 = 32;
pub const FM_SUSPECT_ACQUITTED: u32 = 64;
pub const FM_FAULT_VERS0: u32 = 0;
pub const FM_FAULT_VERSION: u32 = 0;
pub const FM_FAULT_ASRU: &[u8; 5] = b"asru\0";
pub const FM_FAULT_FRU: &[u8; 4] = b"fru\0";
pub const FM_FAULT_FRU_LABEL: &[u8; 10] = b"fru-label\0";
pub const FM_FAULT_CERTAINTY: &[u8; 10] = b"certainty\0";
pub const FM_FAULT_RESOURCE: &[u8; 9] = b"resource\0";
pub const FM_FAULT_LOCATION: &[u8; 9] = b"location\0";
pub const FM_RSRC_VERS0: u32 = 0;
pub const FM_RSRC_VERSION: u32 = 0;
pub const FM_RSRC_RESOURCE: &[u8; 9] = b"resource\0";
pub const FM_RSRC_ASRU_UUID: &[u8; 5] = b"uuid\0";
pub const FM_RSRC_ASRU_CODE: &[u8; 5] = b"code\0";
pub const FM_RSRC_ASRU_FAULTY: &[u8; 7] = b"faulty\0";
pub const FM_RSRC_ASRU_REPAIRED: &[u8; 9] = b"repaired\0";
pub const FM_RSRC_ASRU_REPLACED: &[u8; 9] = b"replaced\0";
pub const FM_RSRC_ASRU_ACQUITTED: &[u8; 10] = b"acquitted\0";
pub const FM_RSRC_ASRU_RESOLVED: &[u8; 9] = b"resolved\0";
pub const FM_RSRC_ASRU_UNUSABLE: &[u8; 9] = b"unusable\0";
pub const FM_RSRC_ASRU_EVENT: &[u8; 6] = b"event\0";
pub const FM_RSRC_XPRT_VERS0: u32 = 0;
pub const FM_RSRC_XPRT_VERSION: u32 = 0;
pub const FM_RSRC_XPRT_UUID: &[u8; 5] = b"uuid\0";
pub const FM_RSRC_XPRT_SUBCLASS: &[u8; 9] = b"subclass\0";
pub const FM_RSRC_XPRT_FAULT_STATUS: &[u8; 13] = b"fault-status\0";
pub const FM_RSRC_XPRT_FAULT_HAS_ASRU: &[u8; 15] = b"fault-has-asru\0";
pub const FM_ENA_FMT0: u32 = 0;
pub const FM_ENA_FMT1: u32 = 1;
pub const FM_ENA_FMT2: u32 = 2;
pub const FM_FMRI_AUTHORITY: &[u8; 10] = b"authority\0";
pub const FM_FMRI_SCHEME: &[u8; 7] = b"scheme\0";
pub const FM_FMRI_SVC_AUTHORITY: &[u8; 14] = b"svc-authority\0";
pub const FM_FMRI_FACILITY: &[u8; 9] = b"facility\0";
pub const FM_FMRI_AUTH_CHASSIS: &[u8; 11] = b"chassis-id\0";
pub const FM_FMRI_AUTH_PRODUCT_SN: &[u8; 11] = b"product-sn\0";
pub const FM_FMRI_AUTH_PRODUCT: &[u8; 11] = b"product-id\0";
pub const FM_FMRI_AUTH_DOMAIN: &[u8; 10] = b"domain-id\0";
pub const FM_FMRI_AUTH_SERVER: &[u8; 10] = b"server-id\0";
pub const FM_FMRI_AUTH_HOST: &[u8; 8] = b"host-id\0";
pub const FM_AUTH_VERS0: u32 = 0;
pub const FM_FMRI_AUTH_VERSION: u32 = 0;
pub const FM_FMRI_SCHEME_FMD: &[u8; 4] = b"fmd\0";
pub const FM_FMRI_SCHEME_DEV: &[u8; 4] = b"dev\0";
pub const FM_FMRI_SCHEME_HC: &[u8; 3] = b"hc\0";
pub const FM_FMRI_SCHEME_SVC: &[u8; 4] = b"svc\0";
pub const FM_FMRI_SCHEME_CPU: &[u8; 4] = b"cpu\0";
pub const FM_FMRI_SCHEME_MEM: &[u8; 4] = b"mem\0";
pub const FM_FMRI_SCHEME_MOD: &[u8; 4] = b"mod\0";
pub const FM_FMRI_SCHEME_PKG: &[u8; 4] = b"pkg\0";
pub const FM_FMRI_SCHEME_LEGACY: &[u8; 10] = b"legacy-hc\0";
pub const FM_FMRI_SCHEME_ZFS: &[u8; 4] = b"zfs\0";
pub const FM_FMRI_SCHEME_SW: &[u8; 3] = b"sw\0";
pub const FM_FMRI_SCHEME_PATH: &[u8; 5] = b"path\0";
pub const FM_FMRI_SCHEME_PCIE: &[u8; 5] = b"pcie\0";
pub const FM_FMD_SCHEME_VERSION: u32 = 0;
pub const FM_DEV_SCHEME_VERSION: u32 = 0;
pub const FM_HC_VERS0: u32 = 0;
pub const FM_HC_SCHEME_VERSION: u32 = 0;
pub const FM_CPU_SCHEME_VERSION: u32 = 1;
pub const FM_MEM_SCHEME_VERSION: u32 = 0;
pub const FM_MOD_SCHEME_VERSION: u32 = 0;
pub const FM_PKG_SCHEME_VERSION: u32 = 0;
pub const FM_LEGACY_SCHEME_VERSION: u32 = 0;
pub const FM_SVC_SCHEME_VERSION: u32 = 0;
pub const FM_ZFS_SCHEME_VERSION: u32 = 0;
pub const FM_SW_SCHEME_VERSION: u32 = 0;
pub const FM_PATH_SCHEME_VERSION: u32 = 0;
pub const FM_PCIE_SCHEME_VERSION: u32 = 0;
pub const FM_FMRI_HC_SERIAL_ID: &[u8; 7] = b"serial\0";
pub const FM_FMRI_HC_PART: &[u8; 5] = b"part\0";
pub const FM_FMRI_HC_REVISION: &[u8; 9] = b"revision\0";
pub const FM_FMRI_HC_ROOT: &[u8; 8] = b"hc-root\0";
pub const FM_FMRI_HC_LIST_SZ: &[u8; 11] = b"hc-list-sz\0";
pub const FM_FMRI_HC_LIST: &[u8; 8] = b"hc-list\0";
pub const FM_FMRI_HC_SPECIFIC: &[u8; 12] = b"hc-specific\0";
pub const FM_FMRI_FACILITY_NAME: &[u8; 14] = b"facility-name\0";
pub const FM_FMRI_FACILITY_TYPE: &[u8; 14] = b"facility-type\0";
pub const FM_FMRI_HC_NAME: &[u8; 8] = b"hc-name\0";
pub const FM_FMRI_HC_ID: &[u8; 6] = b"hc-id\0";
pub const FM_HC_LIST_VERSION: u32 = 0;
pub const FM_FMRI_HC_SPECIFIC_OFFSET: &[u8; 7] = b"offset\0";
pub const FM_FMRI_HC_SPECIFIC_PHYSADDR: &[u8; 9] = b"physaddr\0";
pub const FM_FMRI_FMD_NAME: &[u8; 9] = b"mod-name\0";
pub const FM_FMRI_FMD_VERSION: &[u8; 12] = b"mod-version\0";
pub const FM_FMRI_DEV_ID: &[u8; 6] = b"devid\0";
pub const FM_FMRI_DEV_TGTPTLUN0: &[u8; 17] = b"target-port-l0id\0";
pub const FM_FMRI_DEV_PATH: &[u8; 12] = b"device-path\0";
pub const FM_FMRI_PKG_BASEDIR: &[u8; 12] = b"pkg-basedir\0";
pub const FM_FMRI_PKG_INST: &[u8; 9] = b"pkg-inst\0";
pub const FM_FMRI_PKG_VERSION: &[u8; 12] = b"pkg-version\0";
pub const FM_FMRI_PCIE_LIST: &[u8; 10] = b"pcie-list\0";
pub const FM_FMRI_PCIE_NAME: &[u8; 10] = b"pcie-name\0";
pub const FM_FMRI_PCIE_ID: &[u8; 8] = b"pcie-id\0";
pub const FM_FMRI_SVC_NAME: &[u8; 9] = b"svc-name\0";
pub const FM_FMRI_SVC_INSTANCE: &[u8; 13] = b"svc-instance\0";
pub const FM_FMRI_SVC_CONTRACT_ID: &[u8; 16] = b"svc-contract-id\0";
pub const FM_FMRI_SVC_AUTH_SCOPE: &[u8; 6] = b"scope\0";
pub const FM_FMRI_SVC_AUTH_SYSTEM_FQN: &[u8; 11] = b"system-fqn\0";
pub const FM_FMRI_CPU_ID: &[u8; 6] = b"cpuid\0";
pub const FM_FMRI_CPU_SERIAL_ID: &[u8; 7] = b"serial\0";
pub const FM_FMRI_CPU_MASK: &[u8; 8] = b"cpumask\0";
pub const FM_FMRI_CPU_VID: &[u8; 7] = b"cpuvid\0";
pub const FM_FMRI_CPU_CPUFRU: &[u8; 7] = b"cpufru\0";
pub const FM_FMRI_CPU_CACHE_INDEX: &[u8; 11] = b"cacheindex\0";
pub const FM_FMRI_CPU_CACHE_WAY: &[u8; 9] = b"cacheway\0";
pub const FM_FMRI_CPU_CACHE_BIT: &[u8; 9] = b"cachebit\0";
pub const FM_FMRI_CPU_CACHE_TYPE: &[u8; 10] = b"cachetype\0";
pub const FM_FMRI_CPU_CACHE_TYPE_L2: u32 = 0;
pub const FM_FMRI_CPU_CACHE_TYPE_L3: u32 = 1;
pub const FM_FMRI_LEGACY_HC: &[u8; 10] = b"component\0";
pub const FM_FMRI_LEGACY_HC_PREFIX: &[u8; 17] = b"hc:///component=\0";
pub const FM_FMRI_MEM_UNUM: &[u8; 5] = b"unum\0";
pub const FM_FMRI_MEM_SERIAL_ID: &[u8; 7] = b"serial\0";
pub const FM_FMRI_MEM_PHYSADDR: &[u8; 9] = b"physaddr\0";
pub const FM_FMRI_MEM_MEMCONFIG: &[u8; 10] = b"memconfig\0";
pub const FM_FMRI_MEM_OFFSET: &[u8; 7] = b"offset\0";
pub const FM_FMRI_MOD_PKG: &[u8; 8] = b"mod-pkg\0";
pub const FM_FMRI_MOD_NAME: &[u8; 9] = b"mod-name\0";
pub const FM_FMRI_MOD_ID: &[u8; 7] = b"mod-id\0";
pub const FM_FMRI_MOD_DESC: &[u8; 9] = b"mod-desc\0";
pub const FM_FMRI_ZFS_POOL: &[u8; 5] = b"pool\0";
pub const FM_FMRI_ZFS_VDEV: &[u8; 5] = b"vdev\0";
pub const FM_FMRI_SW_OBJ: &[u8; 7] = b"object\0";
pub const FM_FMRI_SW_OBJ_PATH: &[u8; 5] = b"path\0";
pub const FM_FMRI_SW_OBJ_ROOT: &[u8; 5] = b"root\0";
pub const FM_FMRI_SW_OBJ_PKG: &[u8; 4] = b"pkg\0";
pub const FM_FMRI_SW_SITE: &[u8; 5] = b"site\0";
pub const FM_FMRI_SW_SITE_TOKEN: &[u8; 6] = b"token\0";
pub const FM_FMRI_SW_SITE_MODULE: &[u8; 7] = b"module\0";
pub const FM_FMRI_SW_SITE_FILE: &[u8; 5] = b"file\0";
pub const FM_FMRI_SW_SITE_LINE: &[u8; 5] = b"line\0";
pub const FM_FMRI_SW_SITE_FUNC: &[u8; 5] = b"func\0";
pub const FM_FMRI_SW_CTXT: &[u8; 8] = b"context\0";
pub const FM_FMRI_SW_CTXT_ORIGIN: &[u8; 7] = b"origin\0";
pub const FM_FMRI_SW_CTXT_EXECNAME: &[u8; 9] = b"execname\0";
pub const FM_FMRI_SW_CTXT_PID: &[u8; 4] = b"pid\0";
pub const FM_FMRI_SW_CTXT_ZONE: &[u8; 5] = b"zone\0";
pub const FM_FMRI_SW_CTXT_CTID: &[u8; 5] = b"ctid\0";
pub const FM_FMRI_SW_CTXT_STACK: &[u8; 6] = b"stack\0";
pub const FM_FMRI_PATH_VERSION: &[u8; 20] = b"path-scheme-version\0";
pub const FM_FMRI_PATH: &[u8; 5] = b"path\0";
pub const FM_FMRI_PATH_NAME: &[u8; 10] = b"path-name\0";
pub const FM_FMRI_PATH_INST: &[u8; 14] = b"path-instance\0";
pub const FM_FMRI_PATH_DIGRAPH_SCHEME: &[u8; 20] = b"path-digraph-scheme\0";
pub const FM_NVA_FREE: u32 = 0;
pub const FM_NVA_RETAIN: u32 = 1;
pub type uint_t = ::std::os::raw::c_uint;
pub type ulong_t = ::std::os::raw::c_ulong;
pub const boolean_t_B_FALSE: boolean_t = 0;
pub const boolean_t_B_TRUE: boolean_t = 1;
pub const boolean_t__B_FALSE: boolean_t = 0;
pub const boolean_t__B_TRUE: boolean_t = 1;
pub type boolean_t = ::std::os::raw::c_uint;
pub type __va_list = __builtin_va_list;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nvlist {
    pub nvl_version: i32,
    pub nvl_nvflag: u32,
    pub nvl_priv: u64,
    pub nvl_flag: u32,
    pub nvl_pad: i32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nvlist"][::std::mem::size_of::<nvlist>() - 24usize];
    ["Alignment of nvlist"][::std::mem::align_of::<nvlist>() - 8usize];
    ["Offset of field: nvlist::nvl_version"][::std::mem::offset_of!(nvlist, nvl_version) - 0usize];
    ["Offset of field: nvlist::nvl_nvflag"][::std::mem::offset_of!(nvlist, nvl_nvflag) - 4usize];
    ["Offset of field: nvlist::nvl_priv"][::std::mem::offset_of!(nvlist, nvl_priv) - 8usize];
    ["Offset of field: nvlist::nvl_flag"][::std::mem::offset_of!(nvlist, nvl_flag) - 16usize];
    ["Offset of field: nvlist::nvl_pad"][::std::mem::offset_of!(nvlist, nvl_pad) - 20usize];
};
pub type nvlist_t = nvlist;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __FILE {
    pub __pad: [::std::os::raw::c_long; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __FILE"][::std::mem::size_of::<__FILE>() - 128usize];
    ["Alignment of __FILE"][::std::mem::align_of::<__FILE>() - 8usize];
    ["Offset of field: __FILE::__pad"][::std::mem::offset_of!(__FILE, __pad) - 0usize];
};
pub type FILE = __FILE;
pub type va_list = __va_list;
pub const ddi_node_state_t_DS_INVAL: ddi_node_state_t = -1;
pub const ddi_node_state_t_DS_PROTO: ddi_node_state_t = 0;
pub const ddi_node_state_t_DS_LINKED: ddi_node_state_t = 1;
pub const ddi_node_state_t_DS_BOUND: ddi_node_state_t = 2;
pub const ddi_node_state_t_DS_INITIALIZED: ddi_node_state_t = 3;
pub const ddi_node_state_t_DS_PROBED: ddi_node_state_t = 4;
pub const ddi_node_state_t_DS_ATTACHED: ddi_node_state_t = 5;
pub const ddi_node_state_t_DS_READY: ddi_node_state_t = 6;
pub type ddi_node_state_t = ::std::os::raw::c_int;
pub const ddi_node_class_t_DDI_NC_PROM: ddi_node_class_t = 0;
pub const ddi_node_class_t_DDI_NC_PSEUDO: ddi_node_class_t = 1;
pub type ddi_node_class_t = ::std::os::raw::c_uint;
pub type di_off_t = i32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct di_node {
    pub self_: di_off_t,
    pub parent: di_off_t,
    pub child: di_off_t,
    pub sibling: di_off_t,
    pub next: di_off_t,
    pub node_name: di_off_t,
    pub address: di_off_t,
    pub bind_name: di_off_t,
    pub compat_names: di_off_t,
    pub minor_data: di_off_t,
    pub drv_prop: di_off_t,
    pub sys_prop: di_off_t,
    pub glob_prop: di_off_t,
    pub hw_prop: di_off_t,
    pub parent_data: di_off_t,
    pub driver_data: di_off_t,
    pub multipath_client: di_off_t,
    pub multipath_phci: di_off_t,
    pub devid: di_off_t,
    pub pm_info: di_off_t,
    pub compat_length: ::std::os::raw::c_int,
    pub drv_major: ::std::os::raw::c_int,
    pub instance: ::std::os::raw::c_int,
    pub nodeid: ::std::os::raw::c_int,
    pub node_class: ddi_node_class_t,
    pub attributes: ::std::os::raw::c_int,
    pub state: uint_t,
    pub node_state: ddi_node_state_t,
    pub lnodes: di_off_t,
    pub tgt_links: di_off_t,
    pub src_links: di_off_t,
    pub di_pad1: u32,
    pub user_private_data: u64,
    pub next_vhci: di_off_t,
    pub top_phci: di_off_t,
    pub next_phci: di_off_t,
    pub multipath_component: u32,
    pub flags: u32,
    pub di_pad2: u32,
    pub hp_data: di_off_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of di_node"][::std::mem::size_of::<di_node>() - 168usize];
    ["Alignment of di_node"][::std::mem::align_of::<di_node>() - 8usize];
    ["Offset of field: di_node::self_"][::std::mem::offset_of!(di_node, self_) - 0usize];
    ["Offset of field: di_node::parent"][::std::mem::offset_of!(di_node, parent) - 4usize];
    ["Offset of field: di_node::child"][::std::mem::offset_of!(di_node, child) - 8usize];
    ["Offset of field: di_node::sibling"][::std::mem::offset_of!(di_node, sibling) - 12usize];
    ["Offset of field: di_node::next"][::std::mem::offset_of!(di_node, next) - 16usize];
    ["Offset of field: di_node::node_name"][::std::mem::offset_of!(di_node, node_name) - 20usize];
    ["Offset of field: di_node::address"][::std::mem::offset_of!(di_node, address) - 24usize];
    ["Offset of field: di_node::bind_name"][::std::mem::offset_of!(di_node, bind_name) - 28usize];
    ["Offset of field: di_node::compat_names"]
        [::std::mem::offset_of!(di_node, compat_names) - 32usize];
    ["Offset of field: di_node::minor_data"][::std::mem::offset_of!(di_node, minor_data) - 36usize];
    ["Offset of field: di_node::drv_prop"][::std::mem::offset_of!(di_node, drv_prop) - 40usize];
    ["Offset of field: di_node::sys_prop"][::std::mem::offset_of!(di_node, sys_prop) - 44usize];
    ["Offset of field: di_node::glob_prop"][::std::mem::offset_of!(di_node, glob_prop) - 48usize];
    ["Offset of field: di_node::hw_prop"][::std::mem::offset_of!(di_node, hw_prop) - 52usize];
    ["Offset of field: di_node::parent_data"]
        [::std::mem::offset_of!(di_node, parent_data) - 56usize];
    ["Offset of field: di_node::driver_data"]
        [::std::mem::offset_of!(di_node, driver_data) - 60usize];
    ["Offset of field: di_node::multipath_client"]
        [::std::mem::offset_of!(di_node, multipath_client) - 64usize];
    ["Offset of field: di_node::multipath_phci"]
        [::std::mem::offset_of!(di_node, multipath_phci) - 68usize];
    ["Offset of field: di_node::devid"][::std::mem::offset_of!(di_node, devid) - 72usize];
    ["Offset of field: di_node::pm_info"][::std::mem::offset_of!(di_node, pm_info) - 76usize];
    ["Offset of field: di_node::compat_length"]
        [::std::mem::offset_of!(di_node, compat_length) - 80usize];
    ["Offset of field: di_node::drv_major"][::std::mem::offset_of!(di_node, drv_major) - 84usize];
    ["Offset of field: di_node::instance"][::std::mem::offset_of!(di_node, instance) - 88usize];
    ["Offset of field: di_node::nodeid"][::std::mem::offset_of!(di_node, nodeid) - 92usize];
    ["Offset of field: di_node::node_class"][::std::mem::offset_of!(di_node, node_class) - 96usize];
    ["Offset of field: di_node::attributes"]
        [::std::mem::offset_of!(di_node, attributes) - 100usize];
    ["Offset of field: di_node::state"][::std::mem::offset_of!(di_node, state) - 104usize];
    ["Offset of field: di_node::node_state"]
        [::std::mem::offset_of!(di_node, node_state) - 108usize];
    ["Offset of field: di_node::lnodes"][::std::mem::offset_of!(di_node, lnodes) - 112usize];
    ["Offset of field: di_node::tgt_links"][::std::mem::offset_of!(di_node, tgt_links) - 116usize];
    ["Offset of field: di_node::src_links"][::std::mem::offset_of!(di_node, src_links) - 120usize];
    ["Offset of field: di_node::di_pad1"][::std::mem::offset_of!(di_node, di_pad1) - 124usize];
    ["Offset of field: di_node::user_private_data"]
        [::std::mem::offset_of!(di_node, user_private_data) - 128usize];
    ["Offset of field: di_node::next_vhci"][::std::mem::offset_of!(di_node, next_vhci) - 136usize];
    ["Offset of field: di_node::top_phci"][::std::mem::offset_of!(di_node, top_phci) - 140usize];
    ["Offset of field: di_node::next_phci"][::std::mem::offset_of!(di_node, next_phci) - 144usize];
    ["Offset of field: di_node::multipath_component"]
        [::std::mem::offset_of!(di_node, multipath_component) - 148usize];
    ["Offset of field: di_node::flags"][::std::mem::offset_of!(di_node, flags) - 152usize];
    ["Offset of field: di_node::di_pad2"][::std::mem::offset_of!(di_node, di_pad2) - 156usize];
    ["Offset of field: di_node::hp_data"][::std::mem::offset_of!(di_node, hp_data) - 160usize];
};
pub type di_node_t = *mut di_node;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct di_prom_handle {
    _unused: [u8; 0],
}
pub type di_prom_handle_t = *mut di_prom_handle;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct topo_hdl {
    _unused: [u8; 0],
}
pub type topo_hdl_t = topo_hdl;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct topo_node {
    _unused: [u8; 0],
}
pub type tnode_t = topo_node;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct topo_walk {
    _unused: [u8; 0],
}
pub type topo_walk_t = topo_walk;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct topo_schema_walk {
    _unused: [u8; 0],
}
pub type topo_schema_walk_t = topo_schema_walk;
pub type topo_instance_t = u64;
pub type topo_version_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct topo_list {
    pub l_prev: *mut topo_list,
    pub l_next: *mut topo_list,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of topo_list"][::std::mem::size_of::<topo_list>() - 16usize];
    ["Alignment of topo_list"][::std::mem::align_of::<topo_list>() - 8usize];
    ["Offset of field: topo_list::l_prev"][::std::mem::offset_of!(topo_list, l_prev) - 0usize];
    ["Offset of field: topo_list::l_next"][::std::mem::offset_of!(topo_list, l_next) - 8usize];
};
pub type topo_list_t = topo_list;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct topo_faclist {
    pub tf_list: topo_list_t,
    pub tf_node: *mut tnode_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of topo_faclist"][::std::mem::size_of::<topo_faclist>() - 24usize];
    ["Alignment of topo_faclist"][::std::mem::align_of::<topo_faclist>() - 8usize];
    ["Offset of field: topo_faclist::tf_list"]
        [::std::mem::offset_of!(topo_faclist, tf_list) - 0usize];
    ["Offset of field: topo_faclist::tf_node"]
        [::std::mem::offset_of!(topo_faclist, tf_node) - 16usize];
};
pub type topo_faclist_t = topo_faclist;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct topo_digraph {
    _unused: [u8; 0],
}
pub type topo_digraph_t = topo_digraph;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct topo_vertex {
    _unused: [u8; 0],
}
pub type topo_vertex_t = topo_vertex;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct topo_edge {
    _unused: [u8; 0],
}
pub type topo_edge_t = topo_edge;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct topo_path {
    pub tsp_fmristr: *const ::std::os::raw::c_char,
    pub tsp_fmri: *mut nvlist_t,
    pub tsp_components: topo_list_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of topo_path"][::std::mem::size_of::<topo_path>() - 32usize];
    ["Alignment of topo_path"][::std::mem::align_of::<topo_path>() - 8usize];
    ["Offset of field: topo_path::tsp_fmristr"]
        [::std::mem::offset_of!(topo_path, tsp_fmristr) - 0usize];
    ["Offset of field: topo_path::tsp_fmri"][::std::mem::offset_of!(topo_path, tsp_fmri) - 8usize];
    ["Offset of field: topo_path::tsp_components"]
        [::std::mem::offset_of!(topo_path, tsp_components) - 16usize];
};
pub type topo_path_t = topo_path;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct topo_path_component {
    pub tspc_link: topo_list_t,
    pub tspc_vertex: *mut topo_vertex_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of topo_path_component"][::std::mem::size_of::<topo_path_component>() - 24usize];
    ["Alignment of topo_path_component"][::std::mem::align_of::<topo_path_component>() - 8usize];
    ["Offset of field: topo_path_component::tspc_link"]
        [::std::mem::offset_of!(topo_path_component, tspc_link) - 0usize];
    ["Offset of field: topo_path_component::tspc_vertex"]
        [::std::mem::offset_of!(topo_path_component, tspc_vertex) - 16usize];
};
pub type topo_path_component_t = topo_path_component;
unsafe extern "C" {
    pub fn topo_open(
        arg1: ::std::os::raw::c_int,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut ::std::os::raw::c_int,
    ) -> *mut topo_hdl_t;
}
unsafe extern "C" {
    pub fn topo_close(arg1: *mut topo_hdl_t);
}
unsafe extern "C" {
    pub fn topo_snap_hold(
        arg1: *mut topo_hdl_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn topo_snap_release(arg1: *mut topo_hdl_t);
}
pub type topo_walk_cb_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut topo_hdl_t,
        arg2: *mut tnode_t,
        arg3: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
unsafe extern "C" {
    pub fn topo_walk_init(
        arg1: *mut topo_hdl_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: topo_walk_cb_t,
        arg4: *mut ::std::os::raw::c_void,
        arg5: *mut ::std::os::raw::c_int,
    ) -> *mut topo_walk_t;
}
unsafe extern "C" {
    pub fn topo_walk_step(
        arg1: *mut topo_walk_t,
        arg2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_walk_fini(arg1: *mut topo_walk_t);
}
unsafe extern "C" {
    pub fn topo_hdl_devinfo(arg1: *mut topo_hdl_t) -> di_node_t;
}
unsafe extern "C" {
    pub fn topo_hdl_prominfo(arg1: *mut topo_hdl_t) -> di_prom_handle_t;
}
pub const topo_scheme_type_TOPO_SCHEME_TREE: topo_scheme_type = 0;
pub const topo_scheme_type_TOPO_SCHEME_DIGRAPH: topo_scheme_type = 1;
pub type topo_scheme_type = ::std::os::raw::c_uint;
pub use self::topo_scheme_type as topo_scheme_type_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct topo_scheme_info {
    pub tsi_scheme: *const ::std::os::raw::c_char,
    pub tsi_type: topo_scheme_type_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of topo_scheme_info"][::std::mem::size_of::<topo_scheme_info>() - 16usize];
    ["Alignment of topo_scheme_info"][::std::mem::align_of::<topo_scheme_info>() - 8usize];
    ["Offset of field: topo_scheme_info::tsi_scheme"]
        [::std::mem::offset_of!(topo_scheme_info, tsi_scheme) - 0usize];
    ["Offset of field: topo_scheme_info::tsi_type"]
        [::std::mem::offset_of!(topo_scheme_info, tsi_type) - 8usize];
};
pub type topo_scheme_info_t = topo_scheme_info;
pub type topo_scheme_walk_cb_f = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut topo_hdl_t,
        arg2: *const topo_scheme_info_t,
        arg3: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
unsafe extern "C" {
    pub fn topo_scheme_walk(
        arg1: *mut topo_hdl_t,
        arg2: topo_scheme_walk_cb_f,
        arg3: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_present(
        arg1: *mut topo_hdl_t,
        arg2: *mut nvlist_t,
        arg3: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_replaced(
        arg1: *mut topo_hdl_t,
        arg2: *mut nvlist_t,
        arg3: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_contains(
        arg1: *mut topo_hdl_t,
        arg2: *mut nvlist_t,
        arg3: *mut nvlist_t,
        arg4: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_expand(
        arg1: *mut topo_hdl_t,
        arg2: *mut nvlist_t,
        arg3: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_unusable(
        arg1: *mut topo_hdl_t,
        arg2: *mut nvlist_t,
        arg3: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_service_state(
        arg1: *mut topo_hdl_t,
        arg2: *mut nvlist_t,
        arg3: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_retire(
        arg1: *mut topo_hdl_t,
        arg2: *mut nvlist_t,
        arg3: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_unretire(
        arg1: *mut topo_hdl_t,
        arg2: *mut nvlist_t,
        arg3: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_nvl2str(
        arg1: *mut topo_hdl_t,
        arg2: *mut nvlist_t,
        arg3: *mut *mut ::std::os::raw::c_char,
        arg4: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_str2nvl(
        arg1: *mut topo_hdl_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut *mut nvlist_t,
        arg4: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_asru(
        arg1: *mut topo_hdl_t,
        arg2: *mut nvlist_t,
        arg3: *mut *mut nvlist_t,
        arg4: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_fru(
        arg1: *mut topo_hdl_t,
        arg2: *mut nvlist_t,
        arg3: *mut *mut nvlist_t,
        arg4: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_label(
        arg1: *mut topo_hdl_t,
        arg2: *mut nvlist_t,
        arg3: *mut *mut ::std::os::raw::c_char,
        arg4: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_serial(
        arg1: *mut topo_hdl_t,
        arg2: *mut nvlist_t,
        arg3: *mut *mut ::std::os::raw::c_char,
        arg4: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_compare(
        arg1: *mut topo_hdl_t,
        arg2: *mut nvlist_t,
        arg3: *mut nvlist_t,
        arg4: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_facility(
        arg1: *mut topo_hdl_t,
        arg2: *mut nvlist_t,
        arg3: *const ::std::os::raw::c_char,
        arg4: u32,
        arg5: topo_walk_cb_t,
        arg6: *mut ::std::os::raw::c_void,
        arg7: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_strhash(arg1: *mut topo_hdl_t, arg2: *const ::std::os::raw::c_char)
    -> ulong_t;
}
unsafe extern "C" {
    pub fn topo_fmri_strhash_noauth(
        arg1: *mut topo_hdl_t,
        arg2: *const ::std::os::raw::c_char,
    ) -> ulong_t;
}
unsafe extern "C" {
    pub fn topo_fmri_strcmp(
        arg1: *mut topo_hdl_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
    ) -> boolean_t;
}
unsafe extern "C" {
    pub fn topo_fmri_strcmp_noauth(
        arg1: *mut topo_hdl_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
    ) -> boolean_t;
}
unsafe extern "C" {
    pub fn topo_node_name(arg1: *mut tnode_t) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn topo_node_instance(arg1: *mut tnode_t) -> topo_instance_t;
}
unsafe extern "C" {
    pub fn topo_node_parent(arg1: *mut tnode_t) -> *mut tnode_t;
}
unsafe extern "C" {
    pub fn topo_node_private(arg1: *mut tnode_t) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn topo_node_flags(arg1: *mut tnode_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_node_asru(
        arg1: *mut tnode_t,
        arg2: *mut *mut nvlist_t,
        arg3: *mut nvlist_t,
        arg4: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_node_fru(
        arg1: *mut tnode_t,
        arg2: *mut *mut nvlist_t,
        arg3: *mut nvlist_t,
        arg4: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_node_resource(
        arg1: *mut tnode_t,
        arg2: *mut *mut nvlist_t,
        arg3: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_node_label(
        arg1: *mut tnode_t,
        arg2: *mut *mut ::std::os::raw::c_char,
        arg3: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_node_lookup(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: topo_instance_t,
    ) -> *mut tnode_t;
}
unsafe extern "C" {
    pub fn topo_method_invoke(
        node: *mut tnode_t,
        arg1: *const ::std::os::raw::c_char,
        arg2: topo_version_t,
        arg3: *mut nvlist_t,
        arg4: *mut *mut nvlist_t,
        arg5: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_method_supported(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: topo_version_t,
    ) -> boolean_t;
}
unsafe extern "C" {
    pub fn topo_node_facility(
        arg1: *mut topo_hdl_t,
        arg2: *mut tnode_t,
        arg3: *const ::std::os::raw::c_char,
        arg4: u32,
        arg5: *mut topo_faclist_t,
        arg6: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_node_child_walk(
        arg1: *mut topo_hdl_t,
        arg2: *mut tnode_t,
        arg3: topo_walk_cb_t,
        arg4: *mut ::std::os::raw::c_void,
        arg5: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_node_occupied(arg1: *mut tnode_t, arg2: *mut boolean_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_get_int32(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut i32,
        arg5: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_get_uint32(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut u32,
        arg5: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_get_int64(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut i64,
        arg5: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_get_uint64(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut u64,
        arg5: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_get_double(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut f64,
        arg5: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_get_string(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut *mut ::std::os::raw::c_char,
        arg5: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_get_fmri(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut *mut nvlist_t,
        arg5: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_get_int32_array(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut *mut i32,
        arg5: *mut uint_t,
        arg6: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_get_uint32_array(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut *mut u32,
        arg5: *mut uint_t,
        arg6: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_get_int64_array(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut *mut i64,
        arg5: *mut uint_t,
        arg6: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_get_uint64_array(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut *mut u64,
        arg5: *mut uint_t,
        arg6: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_get_string_array(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut *mut *mut ::std::os::raw::c_char,
        arg5: *mut uint_t,
        arg6: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_get_fmri_array(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut *mut *mut nvlist_t,
        arg5: *mut uint_t,
        arg6: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_set_int32(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
        arg5: i32,
        arg6: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_set_uint32(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
        arg5: u32,
        arg6: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_set_int64(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
        arg5: i64,
        arg6: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_set_uint64(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
        arg5: u64,
        arg6: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_set_double(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
        arg5: f64,
        arg6: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_set_string(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
        arg5: *const ::std::os::raw::c_char,
        arg6: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_set_fmri(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
        arg5: *const nvlist_t,
        arg6: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_set_int32_array(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
        arg5: *mut i32,
        arg6: uint_t,
        arg7: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_set_uint32_array(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
        arg5: *mut u32,
        arg6: uint_t,
        arg7: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_set_int64_array(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
        arg5: *mut i64,
        arg6: uint_t,
        arg7: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_set_uint64_array(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
        arg5: *mut u64,
        arg6: uint_t,
        arg7: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_set_string_array(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
        arg5: *mut *const ::std::os::raw::c_char,
        arg6: uint_t,
        arg7: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_set_fmri_array(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
        arg5: *mut *const nvlist_t,
        arg6: uint_t,
        arg7: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
pub const topo_prop_errno_ETOPO_PROP_UNKNOWN: topo_prop_errno = 3000;
pub const topo_prop_errno_ETOPO_PROP_NOENT: topo_prop_errno = 3001;
pub const topo_prop_errno_ETOPO_PROP_DEFD: topo_prop_errno = 3002;
pub const topo_prop_errno_ETOPO_PROP_NOMEM: topo_prop_errno = 3003;
pub const topo_prop_errno_ETOPO_PROP_TYPE: topo_prop_errno = 3004;
pub const topo_prop_errno_ETOPO_PROP_NAME: topo_prop_errno = 3005;
pub const topo_prop_errno_ETOPO_PROP_NOINHERIT: topo_prop_errno = 3006;
pub const topo_prop_errno_ETOPO_PROP_NVL: topo_prop_errno = 3007;
pub const topo_prop_errno_ETOPO_PROP_METHOD: topo_prop_errno = 3008;
pub const topo_prop_errno_ETOPO_PROP_END: topo_prop_errno = 3009;
pub type topo_prop_errno = ::std::os::raw::c_uint;
pub use self::topo_prop_errno as topo_prop_errno_t;
pub const topo_method_errno_ETOPO_METHOD_UNKNOWN: topo_method_errno = 3100;
pub const topo_method_errno_ETOPO_METHOD_INVAL: topo_method_errno = 3101;
pub const topo_method_errno_ETOPO_METHOD_NOTSUP: topo_method_errno = 3102;
pub const topo_method_errno_ETOPO_METHOD_FAIL: topo_method_errno = 3103;
pub const topo_method_errno_ETOPO_METHOD_VEROLD: topo_method_errno = 3104;
pub const topo_method_errno_ETOPO_METHOD_VERNEW: topo_method_errno = 3105;
pub const topo_method_errno_ETOPO_METHOD_NOMEM: topo_method_errno = 3106;
pub const topo_method_errno_ETOPO_METHOD_DEFD: topo_method_errno = 3107;
pub const topo_method_errno_ETOPO_METHOD_END: topo_method_errno = 3108;
pub type topo_method_errno = ::std::os::raw::c_uint;
pub use self::topo_method_errno as topo_method_errno_t;
pub const topo_fmri_errno_ETOPO_FMRI_UNKNOWN: topo_fmri_errno = 3200;
pub const topo_fmri_errno_ETOPO_FMRI_NVL: topo_fmri_errno = 3201;
pub const topo_fmri_errno_ETOPO_FMRI_VERSION: topo_fmri_errno = 3202;
pub const topo_fmri_errno_ETOPO_FMRI_MALFORM: topo_fmri_errno = 3203;
pub const topo_fmri_errno_ETOPO_FMRI_NOMEM: topo_fmri_errno = 3204;
pub const topo_fmri_errno_ETOPO_FMRI_END: topo_fmri_errno = 3205;
pub type topo_fmri_errno = ::std::os::raw::c_uint;
pub use self::topo_fmri_errno as topo_fmri_errno_t;
pub const topo_hdl_errno_ETOPO_HDL_UNKNOWN: topo_hdl_errno = 3300;
pub const topo_hdl_errno_ETOPO_HDL_ABIVER: topo_hdl_errno = 3301;
pub const topo_hdl_errno_ETOPO_HDL_SNAP: topo_hdl_errno = 3302;
pub const topo_hdl_errno_ETOPO_HDL_INVAL: topo_hdl_errno = 3303;
pub const topo_hdl_errno_ETOPO_HDL_UUID: topo_hdl_errno = 3304;
pub const topo_hdl_errno_ETOPO_HDL_NOMEM: topo_hdl_errno = 3305;
pub const topo_hdl_errno_ETOPO_HDL_END: topo_hdl_errno = 3306;
pub type topo_hdl_errno = ::std::os::raw::c_uint;
pub use self::topo_hdl_errno as topo_hdl_errno_t;
unsafe extern "C" {
    pub fn topo_strerror(arg1: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn topo_hdl_strfree(arg1: *mut topo_hdl_t, arg2: *mut ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn topo_hdl_strfreev(
        arg1: *mut topo_hdl_t,
        arg2: *mut *mut ::std::os::raw::c_char,
        arg3: uint_t,
    );
}
unsafe extern "C" {
    pub fn topo_debug_set(
        arg1: *mut topo_hdl_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
    );
}
pub const topo_stability_TOPO_STABILITY_UNKNOWN: topo_stability = 0;
pub const topo_stability_TOPO_STABILITY_INTERNAL: topo_stability = 1;
pub const topo_stability_TOPO_STABILITY_PRIVATE: topo_stability = 2;
pub const topo_stability_TOPO_STABILITY_OBSOLETE: topo_stability = 3;
pub const topo_stability_TOPO_STABILITY_EXTERNAL: topo_stability = 4;
pub const topo_stability_TOPO_STABILITY_UNSTABLE: topo_stability = 5;
pub const topo_stability_TOPO_STABILITY_EVOLVING: topo_stability = 6;
pub const topo_stability_TOPO_STABILITY_STABLE: topo_stability = 7;
pub const topo_stability_TOPO_STABILITY_STANDARD: topo_stability = 8;
pub type topo_stability = ::std::os::raw::c_uint;
pub use self::topo_stability as topo_stability_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct topo_pgroup_info {
    pub tpi_name: *const ::std::os::raw::c_char,
    pub tpi_namestab: topo_stability_t,
    pub tpi_datastab: topo_stability_t,
    pub tpi_version: topo_version_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of topo_pgroup_info"][::std::mem::size_of::<topo_pgroup_info>() - 24usize];
    ["Alignment of topo_pgroup_info"][::std::mem::align_of::<topo_pgroup_info>() - 8usize];
    ["Offset of field: topo_pgroup_info::tpi_name"]
        [::std::mem::offset_of!(topo_pgroup_info, tpi_name) - 0usize];
    ["Offset of field: topo_pgroup_info::tpi_namestab"]
        [::std::mem::offset_of!(topo_pgroup_info, tpi_namestab) - 8usize];
    ["Offset of field: topo_pgroup_info::tpi_datastab"]
        [::std::mem::offset_of!(topo_pgroup_info, tpi_datastab) - 12usize];
    ["Offset of field: topo_pgroup_info::tpi_version"]
        [::std::mem::offset_of!(topo_pgroup_info, tpi_version) - 16usize];
};
pub type topo_pgroup_info_t = topo_pgroup_info;
unsafe extern "C" {
    pub fn topo_name2stability(arg1: *const ::std::os::raw::c_char) -> topo_stability_t;
}
unsafe extern "C" {
    pub fn topo_stability2name(arg1: topo_stability_t) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn topo_pgroup_destroy(arg1: *mut tnode_t, arg2: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn topo_pgroup_info(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut ::std::os::raw::c_int,
    ) -> *mut topo_pgroup_info_t;
}
pub const topo_type_t_TOPO_TYPE_INVALID: topo_type_t = 0;
pub const topo_type_t_TOPO_TYPE_BOOLEAN: topo_type_t = 1;
pub const topo_type_t_TOPO_TYPE_INT32: topo_type_t = 2;
pub const topo_type_t_TOPO_TYPE_UINT32: topo_type_t = 3;
pub const topo_type_t_TOPO_TYPE_INT64: topo_type_t = 4;
pub const topo_type_t_TOPO_TYPE_UINT64: topo_type_t = 5;
pub const topo_type_t_TOPO_TYPE_STRING: topo_type_t = 6;
pub const topo_type_t_TOPO_TYPE_TIME: topo_type_t = 7;
pub const topo_type_t_TOPO_TYPE_SIZE: topo_type_t = 8;
pub const topo_type_t_TOPO_TYPE_FMRI: topo_type_t = 9;
pub const topo_type_t_TOPO_TYPE_INT32_ARRAY: topo_type_t = 10;
pub const topo_type_t_TOPO_TYPE_UINT32_ARRAY: topo_type_t = 11;
pub const topo_type_t_TOPO_TYPE_INT64_ARRAY: topo_type_t = 12;
pub const topo_type_t_TOPO_TYPE_UINT64_ARRAY: topo_type_t = 13;
pub const topo_type_t_TOPO_TYPE_STRING_ARRAY: topo_type_t = 14;
pub const topo_type_t_TOPO_TYPE_FMRI_ARRAY: topo_type_t = 15;
pub const topo_type_t_TOPO_TYPE_DOUBLE: topo_type_t = 16;
pub type topo_type_t = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn topo_prop_getprops(arg1: *mut tnode_t, err: *mut ::std::os::raw::c_int)
    -> *mut nvlist_t;
}
unsafe extern "C" {
    pub fn topo_prop_getprop(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut nvlist_t,
        arg5: *mut *mut nvlist_t,
        arg6: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_getpgrp(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut *mut nvlist_t,
        arg4: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_prop_setprop(
        arg1: *mut tnode_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut nvlist_t,
        arg4: ::std::os::raw::c_int,
        arg5: *mut nvlist_t,
        arg6: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_getprop(
        arg1: *mut topo_hdl_t,
        arg2: *mut nvlist_t,
        arg3: *const ::std::os::raw::c_char,
        arg4: *const ::std::os::raw::c_char,
        arg5: *mut nvlist_t,
        arg6: *mut *mut nvlist_t,
        arg7: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_getpgrp(
        arg1: *mut topo_hdl_t,
        arg2: *mut nvlist_t,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut *mut nvlist_t,
        arg5: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_fmri_setprop(
        arg1: *mut topo_hdl_t,
        arg2: *mut nvlist_t,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut nvlist_t,
        arg5: ::std::os::raw::c_int,
        arg6: *mut nvlist_t,
        arg7: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_pgroup_hcset(arg1: *mut tnode_t, arg2: *mut nvlist_t);
}
unsafe extern "C" {
    pub fn topo_xml_print(
        arg1: *mut topo_hdl_t,
        arg2: *mut FILE,
        scheme: *const ::std::os::raw::c_char,
        arg3: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_hdl_alloc(arg1: *mut topo_hdl_t, arg2: usize) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn topo_hdl_zalloc(arg1: *mut topo_hdl_t, arg2: usize) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn topo_hdl_free(arg1: *mut topo_hdl_t, arg2: *mut ::std::os::raw::c_void, arg3: usize);
}
unsafe extern "C" {
    pub fn topo_hdl_nvalloc(
        arg1: *mut topo_hdl_t,
        arg2: *mut *mut nvlist_t,
        arg3: uint_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_hdl_nvdup(
        arg1: *mut topo_hdl_t,
        arg2: *mut nvlist_t,
        arg3: *mut *mut nvlist_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_hdl_strdup(
        arg1: *mut topo_hdl_t,
        arg2: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn topo_hdl_vasprintf(
        arg1: *mut topo_hdl_t,
        arg2: *mut *mut ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut __va_list_tag,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_hdl_asprintf(
        arg1: *mut topo_hdl_t,
        arg2: *mut *mut ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_digraph_get(
        arg1: *mut topo_hdl_t,
        arg2: *const ::std::os::raw::c_char,
    ) -> *mut topo_digraph_t;
}
unsafe extern "C" {
    pub fn topo_vertex_iter(
        arg1: *mut topo_hdl_t,
        arg2: *mut topo_digraph_t,
        arg3: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut topo_hdl_t,
                arg2: *mut topo_vertex_t,
                arg3: boolean_t,
                arg4: *mut ::std::os::raw::c_void,
            ) -> ::std::os::raw::c_int,
        >,
        arg4: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_vertex_node(arg1: *mut topo_vertex_t) -> *mut tnode_t;
}
unsafe extern "C" {
    pub fn topo_edge_iter(
        arg1: *mut topo_hdl_t,
        arg2: *mut topo_vertex_t,
        arg3: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut topo_hdl_t,
                arg2: *mut topo_edge_t,
                arg3: boolean_t,
                arg4: *mut ::std::os::raw::c_void,
            ) -> ::std::os::raw::c_int,
        >,
        arg4: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_digraph_paths(
        arg1: *mut topo_hdl_t,
        arg2: *mut topo_digraph_t,
        arg3: *mut topo_vertex_t,
        arg4: *mut topo_vertex_t,
        arg5: *mut *mut *mut topo_path_t,
        arg6: *mut uint_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_path_destroy(arg1: *mut topo_hdl_t, arg2: *mut topo_path_t);
}
unsafe extern "C" {
    pub fn topo_digraph_serialize(
        arg1: *mut topo_hdl_t,
        arg2: *mut topo_digraph_t,
        arg3: *mut FILE,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn topo_digraph_deserialize(
        arg1: *mut topo_hdl_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: usize,
    ) -> *mut topo_digraph_t;
}
unsafe extern "C" {
    pub fn topo_node_vertex(arg1: *mut tnode_t) -> *mut topo_vertex_t;
}
unsafe extern "C" {
    pub fn topo_sensor_type_name(arg1: u32, arg2: *mut ::std::os::raw::c_char, arg3: usize);
}
unsafe extern "C" {
    pub fn topo_sensor_units_name(arg1: u32, arg2: *mut ::std::os::raw::c_char, arg3: usize);
}
unsafe extern "C" {
    pub fn topo_led_type_name(arg1: u32, arg2: *mut ::std::os::raw::c_char, arg3: usize);
}
unsafe extern "C" {
    pub fn topo_led_state_name(arg1: u32, arg2: *mut ::std::os::raw::c_char, arg3: usize);
}
unsafe extern "C" {
    pub fn topo_sensor_state_name(
        arg1: u32,
        arg2: u32,
        arg3: *mut ::std::os::raw::c_char,
        len: usize,
    );
}
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_UNSPECIFIED: topo_sensor_unit = 0;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_DEGREES_C: topo_sensor_unit = 1;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_DEGREES_F: topo_sensor_unit = 2;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_DEGREES_K: topo_sensor_unit = 3;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_VOLTS: topo_sensor_unit = 4;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_AMPS: topo_sensor_unit = 5;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_WATTS: topo_sensor_unit = 6;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_JOULES: topo_sensor_unit = 7;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_COULOMBS: topo_sensor_unit = 8;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_VA: topo_sensor_unit = 9;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_NITS: topo_sensor_unit = 10;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_LUMEN: topo_sensor_unit = 11;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_LUX: topo_sensor_unit = 12;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_CANDELA: topo_sensor_unit = 13;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_KPA: topo_sensor_unit = 14;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_PSI: topo_sensor_unit = 15;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_NEWTON: topo_sensor_unit = 16;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_CFM: topo_sensor_unit = 17;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_RPM: topo_sensor_unit = 18;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_HZ: topo_sensor_unit = 19;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_MICROSEC: topo_sensor_unit = 20;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_MILLISEC: topo_sensor_unit = 21;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_SECS: topo_sensor_unit = 22;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_MIN: topo_sensor_unit = 23;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_HOUR: topo_sensor_unit = 24;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_DAY: topo_sensor_unit = 25;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_WEEK: topo_sensor_unit = 26;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_MIL: topo_sensor_unit = 27;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_INCHES: topo_sensor_unit = 28;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_FEET: topo_sensor_unit = 29;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_CUB_INCH: topo_sensor_unit = 30;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_CUB_FEET: topo_sensor_unit = 31;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_MM: topo_sensor_unit = 32;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_CM: topo_sensor_unit = 33;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_METERS: topo_sensor_unit = 34;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_CUB_CM: topo_sensor_unit = 35;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_CUB_METER: topo_sensor_unit = 36;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_LITERS: topo_sensor_unit = 37;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_FLUID_OUNCE: topo_sensor_unit = 38;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_RADIANS: topo_sensor_unit = 39;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_STERADIANS: topo_sensor_unit = 40;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_REVOLUTIONS: topo_sensor_unit = 41;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_CYCLES: topo_sensor_unit = 42;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_GRAVITIES: topo_sensor_unit = 43;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_OUNCE: topo_sensor_unit = 44;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_POUND: topo_sensor_unit = 45;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_FOOT_POUND: topo_sensor_unit = 46;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_OZ_INCH: topo_sensor_unit = 47;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_GAUSS: topo_sensor_unit = 48;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_GILBERTS: topo_sensor_unit = 49;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_HENRY: topo_sensor_unit = 50;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_MILHENRY: topo_sensor_unit = 51;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_FARAD: topo_sensor_unit = 52;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_MICROFARAD: topo_sensor_unit = 53;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_OHMS: topo_sensor_unit = 54;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_SIEMENS: topo_sensor_unit = 55;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_MOLE: topo_sensor_unit = 56;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_BECQUEREL: topo_sensor_unit = 57;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_PPM: topo_sensor_unit = 58;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_RESERVED1: topo_sensor_unit = 59;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_DECIBELS: topo_sensor_unit = 60;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_DBA: topo_sensor_unit = 61;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_DBC: topo_sensor_unit = 62;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_GRAY: topo_sensor_unit = 63;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_SIEVERT: topo_sensor_unit = 64;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_COLOR_TEMP_K: topo_sensor_unit = 65;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_BIT: topo_sensor_unit = 66;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_KILOBIT: topo_sensor_unit = 67;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_MEGABIT: topo_sensor_unit = 68;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_GIGABIT: topo_sensor_unit = 69;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_BYTE: topo_sensor_unit = 70;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_KILOBYTE: topo_sensor_unit = 71;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_MEGABYTE: topo_sensor_unit = 72;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_GIGABYTE: topo_sensor_unit = 73;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_WORD: topo_sensor_unit = 74;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_DWORD: topo_sensor_unit = 75;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_QWORD: topo_sensor_unit = 76;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_MEMLINE: topo_sensor_unit = 77;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_HIT: topo_sensor_unit = 78;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_MISS: topo_sensor_unit = 79;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_RETRY: topo_sensor_unit = 80;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_RESET: topo_sensor_unit = 81;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_OVERFLOW: topo_sensor_unit = 82;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_UNDERRUN: topo_sensor_unit = 83;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_COLLISION: topo_sensor_unit = 84;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_PACKETS: topo_sensor_unit = 85;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_MESSAGES: topo_sensor_unit = 86;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_CHARACTERS: topo_sensor_unit = 87;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_ERROR: topo_sensor_unit = 88;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_CE: topo_sensor_unit = 89;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_UE: topo_sensor_unit = 90;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_FATAL_ERROR: topo_sensor_unit = 91;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_GRAMS: topo_sensor_unit = 92;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_PERCENT: topo_sensor_unit = 512;
pub const topo_sensor_unit_TOPO_SENSOR_UNITS_NONE: topo_sensor_unit = 513;
pub type topo_sensor_unit = ::std::os::raw::c_uint;
pub use self::topo_sensor_unit as topo_sensor_unit_t;
pub const topo_led_state_TOPO_LED_STATE_OFF: topo_led_state = 0;
pub const topo_led_state_TOPO_LED_STATE_ON: topo_led_state = 1;
pub type topo_led_state = ::std::os::raw::c_uint;
pub use self::topo_led_state as topo_led_state_t;
pub const topo_led_type_TOPO_LED_TYPE_SERVICE: topo_led_type = 0;
pub const topo_led_type_TOPO_LED_TYPE_LOCATE: topo_led_type = 1;
pub const topo_led_type_TOPO_LED_TYPE_OK2RM: topo_led_type = 2;
pub const topo_led_type_TOPO_LED_TYPE_PRESENT: topo_led_type = 3;
pub type topo_led_type = ::std::os::raw::c_uint;
pub use self::topo_led_type as topo_led_type_t;
pub const topo_slot_type_TOPO_SLOT_TYPE_DIMM: topo_slot_type = 1;
pub const topo_slot_type_TOPO_SLOT_TYPE_UFM: topo_slot_type = 2;
pub const topo_slot_type_TOPO_SLOT_TYPE_M2: topo_slot_type = 3;
pub const topo_slot_type_TOPO_SLOT_TYPE_CEM: topo_slot_type = 4;
pub type topo_slot_type = ::std::os::raw::c_uint;
pub use self::topo_slot_type as topo_slot_type_t;
pub const topo_ufm_slot_mode_TOPO_UFM_SLOT_MODE_NONE: topo_ufm_slot_mode = 1;
pub const topo_ufm_slot_mode_TOPO_UFM_SLOT_MODE_RO: topo_ufm_slot_mode = 2;
pub const topo_ufm_slot_mode_TOPO_UFM_SLOT_MODE_WO: topo_ufm_slot_mode = 3;
pub const topo_ufm_slot_mode_TOPO_UFM_SLOT_MODE_RW: topo_ufm_slot_mode = 4;
pub type topo_ufm_slot_mode = ::std::os::raw::c_uint;
pub use self::topo_ufm_slot_mode as topo_ufm_slot_mode_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct topo_ufm_slot_info {
    pub usi_slotid: u32,
    pub usi_mode: topo_ufm_slot_mode_t,
    pub usi_version: *const ::std::os::raw::c_char,
    pub usi_active: boolean_t,
    pub usi_extra: *mut nvlist_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of topo_ufm_slot_info"][::std::mem::size_of::<topo_ufm_slot_info>() - 32usize];
    ["Alignment of topo_ufm_slot_info"][::std::mem::align_of::<topo_ufm_slot_info>() - 8usize];
    ["Offset of field: topo_ufm_slot_info::usi_slotid"]
        [::std::mem::offset_of!(topo_ufm_slot_info, usi_slotid) - 0usize];
    ["Offset of field: topo_ufm_slot_info::usi_mode"]
        [::std::mem::offset_of!(topo_ufm_slot_info, usi_mode) - 4usize];
    ["Offset of field: topo_ufm_slot_info::usi_version"]
        [::std::mem::offset_of!(topo_ufm_slot_info, usi_version) - 8usize];
    ["Offset of field: topo_ufm_slot_info::usi_active"]
        [::std::mem::offset_of!(topo_ufm_slot_info, usi_active) - 16usize];
    ["Offset of field: topo_ufm_slot_info::usi_extra"]
        [::std::mem::offset_of!(topo_ufm_slot_info, usi_extra) - 24usize];
};
pub type topo_ufm_slot_info_t = topo_ufm_slot_info;
pub type __builtin_va_list = [__va_list_tag; 1usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __va_list_tag {
    pub gp_offset: ::std::os::raw::c_uint,
    pub fp_offset: ::std::os::raw::c_uint,
    pub overflow_arg_area: *mut ::std::os::raw::c_void,
    pub reg_save_area: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __va_list_tag"][::std::mem::size_of::<__va_list_tag>() - 24usize];
    ["Alignment of __va_list_tag"][::std::mem::align_of::<__va_list_tag>() - 8usize];
    ["Offset of field: __va_list_tag::gp_offset"]
        [::std::mem::offset_of!(__va_list_tag, gp_offset) - 0usize];
    ["Offset of field: __va_list_tag::fp_offset"]
        [::std::mem::offset_of!(__va_list_tag, fp_offset) - 4usize];
    ["Offset of field: __va_list_tag::overflow_arg_area"]
        [::std::mem::offset_of!(__va_list_tag, overflow_arg_area) - 8usize];
    ["Offset of field: __va_list_tag::reg_save_area"]
        [::std::mem::offset_of!(__va_list_tag, reg_save_area) - 16usize];
};
